Update with how I like this project to work

diff --git a/libexec/sub-commands b/libexec/sub-commands
--- a/libexec/sub-commands
+++ b/libexec/sub-commands
@@ -1,42 +1,41 @@
 #!/usr/bin/env bash
 # Usage: sub commands
 # Summary: List all sub commands
-# Help: This command is mostly used for autocompletion in various shells, and for `sub help`.
-# Also, this command helps find commands that are named the same as potentially builtin shell commands (which, cd, etc)
+#
+# NAME
+#   sub commands -- list sub commands
+#
+# SYNOPSIS
+#   sub commands
+#
+# DESCRIPTION
+#   This command is mostly used for autocompletion in various shells, and for
+#   `sub help`.
 
-set -e
-
-# Provide sub completions
-if [ "$1" = "--complete" ]; then
-  echo --sh
-  echo --no-sh
-  exit
+if [[ "$DEBUG" ]]; then
+  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
+  set -x
 fi
 
-if [ "$1" = "--sh" ]; then
-  sh=1
-  shift
-elif [ "$1" = "--no-sh" ]; then
-  nosh=1
-  shift
+if [[ -z "$_SUB_ROOT" ]]; then
+  echo "Error: Must run \`${0//*\/sub-/sub }' instead."
+  exit 1
 fi
 
-shopt -s nullglob
+set -euo pipefail
 
-{ for path in ${PATH//:/$'\n'}; do
-    for command in "${path}/sub-"*; do
-      command="${command##*sub-}"
-      if [ -n "$sh" ]; then
-        if [ ${command:0:3} = "sh-" ]; then
-          echo ${command##sh-}
-        fi
-      elif [ -n "$nosh" ]; then
-        if [ ${command:0:3} != "sh-" ]; then
-          echo ${command##sh-}
-        fi
-      else
-        echo ${command##sh-}
+main() {
+  shopt -s nullglob
+
+  {
+    for command in "$_SUB_ROOT/libexec/sub-"*; do
+      if [[ -x "$command" ]]; then
+        echo "${command##*/sub-}"
       fi
     done
-  done
-} | sort | uniq
+  } | sort
+
+  shopt -u nullglob
+}
+
+main "$@"
diff --git a/libexec/sub-help b/libexec/sub-help
--- a/libexec/sub-help
+++ b/libexec/sub-help
@@ -1,101 +1,367 @@
 #!/usr/bin/env bash
-set -e
+# Usage: sub help [options] [--] <sub-command>
+# Summary: Prints help for sub commands
+#
+# NAME
+#   sub help -- print help for sub commands
+#
+# SYNOPSIS
+#   sub help [options] [--] <sub-command>
+#
+# DESCRIPTION
+#   Print help messages for the various sub commands.
+#
+# OPTIONS
+#   -u, --usage
+#       Print usage and exit.
+#
+#   -e code, --exit code
+#       Exit code to return after printing help, default is 0
+#
+#   -f flag, --flag flag
+#       Help flag that was passed to a program, `-h` or `--help`
+#
+# EXAMPLES
+#   Normal operation:
+#
+#   Show an overview of all sub commands
+#   $ sub help
+#
+#   Get help for a specific sub command
+#   $ sub help COMMAND
+#
+#   The `-f flag` option is useful for other sub scripts to accept
+#   `-h` or `--help` as arguments. For example:
+#
+#     case "${1}" in
+#       -h | --help) exec sub-help --flag "${1}" COMMAND;;
+#       ...
+#     esac
+#
+#   When the script receives `-h` it will print a single usage line only. When
+#   `--help` is received full help info is printed.
+#
+#   The `-e code` option is useful for sub scripts to print help info when
+#   they are called incorrectly. For example, if a script accepted one
+#   argument only:
+#
+#     if [[ ${#} -ne 1 ]]; then
+#       warn "Invalid usage"
+#       exec sub-help --exit 1 --flag --help some-script
+#     fi
+#
+# WRITING DOCS
+#   Documentation is contained within C style comments (eg: `# `) at the top
+#   of a sub script, just under the shebang. There are three sections:
+#
+#     Usage:   Short one line usage example
+#     Summary: Short one line summary of the script
+#     Help:    Multiline text containing extended help info
+#
+#   For example:
+#
+#     #!/usr/bin/env bash
+#     # Usage: sub foo [options]
+#     # Summary: It foobars!
+#     #
+#     # SYNOPSIS
+#     #   sub foo [options]
+#     #
+#     # OPTIONS
+#     #   -h, --help
+#     #       Print help info
+#
+#     echo "Foobar!"
+#
+#     case "${1}" in
+#       -h | --help) exec sub-help --flag "${1}" foo;;
+#     esac
+#
+#   When running `sub foo -h`, the usage will be printed:
+#
+#     $ sub foo -h
+#     Usage: sub foo [options
+#
+#   When running `sub foo --help` or `sub help foo`, the full help is
+#   printed:
+#
+#     $ sub foo --help
+#     Usage: sub foo [options]
+#
+#     SYNOPSIS
+#       sub foo [options]
+#
+#     OPTIONS
+#       -h, --help
+#           Print help info
+#
+#   When running `sub help`, this command will be included in the list with
+#   its summary:
+#
+#   ...
+#   COMMANDS
+#        foo                  It foobars!
+#   ...
 
-print_summaries() {
-  local commands=()
-  local summaries=()
-  local longest_command=0
-  local command
+if [[ "$DEBUG" ]]; then
+  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
+  set -x
+fi
 
-  for command in $(sub-commands); do
-    local file="$(command_path "$command")"
-    if [ ! -h "$file" ]; then
-      local summary="$(summary "$file")"
-      if [ -n "$summary" ]; then
-        commands["${#commands[@]}"]="$command"
-        summaries["${#summaries[@]}"]="$summary"
+if [[ -z "$_SUB_ROOT" ]]; then
+  echo "Error: Must run \`${0//*\/sub-/sub }' instead."
+  exit 1
+fi
 
-        if [ "${#command}" -gt "$longest_command" ]; then
-          longest_command="${#command}"
-        fi
-      fi
-    fi
-  done
+set -euo pipefail
 
-  local index
-  local columns="$(tput cols)"
-  local summary_length=$(( $columns - $longest_command - 5 ))
+[[ -t 1 ]] && ansi=1
 
-  for (( index=0; index < ${#commands[@]}; index++ )); do
-    printf "   %-${longest_command}s  %s\n" "${commands[$index]}" \
-      "$(truncate "$summary_length" "${summaries[$index]}")"
-  done
+# Provide sub completions
+completions() {
+  exec sub-commands
+  exit 0
 }
 
-print_help() {
-  local file="$1"
-  local usage="$(usage "$file")"
+# Prints the sub command path if it can be found.
+#
+# $1 - Name
+command_path() {
+  local command_name command_path
 
-  if [ -n "$usage" ]; then
-    echo "$usage"
+  command_name="${1:-}"
+  command_path="$_SUB_ROOT/libexec/sub-$command_name"
 
-    local help="$(help "$file")"
-    [ -n "$help" ] && echo && echo "$help"
+  if [[ -x "$command_path" ]]; then
+    printf "%s\\n" "$command_path"
   else
-    echo "Sorry, this command isn't documented yet."
+    true
   fi
 }
 
-command_path() {
-  command -v "sub-$command" || command -v "sub-sh-$command" || true
-}
-
-summary() {
-  sed -n "s/^# Summary: \(.*\)/\1/p" "$1"
-}
-
-usage() {
-  sed -n "s/^# \(Usage: .*\)/\1/p" "$1"
-}
-
-help() {
-  awk '/^[^#]/{p=0} /^# Help:/{p=1} p' "$1" | sed "s/^# Help: //;s/^# //;s/^#//"
-}
-
+# Truncates a string by the given length.
+#
+# $1 - Max length
+# $2 - String
 truncate() {
   local max_length="$1"
   local string="$2"
 
-  if [ "${#string}" -gt "$max_length" ]; then
-    local length=$(( $max_length - 3 ))
+  if [[ "${ansi:-}" ]] && [[ "${#string}" -gt "$max_length" ]]; then
+    local length=$(( max_length - 3 ))
     echo "${string:0:$length}..."
   else
     echo "$string"
   fi
 }
 
-# Provide sub completions
-if [ "$1" = "--complete" ]; then
-  exec "sub-commands"
-  exit
-fi
+# Print all sub commands and their summaries.
+print_summaries() {
+  local commands=()
+  local summaries=()
+  local longest_command=0
+  local command summary_length index columns
 
-command="$1"
-case "$command" in
-"") echo "Usage: sub <command> [<args>]
+  for command in $(sub-commands); do
+    local file
 
-Some useful sub commands are:
-$(print_summaries)
+    file="$(command_path "$command")"
 
-See 'sub help <command>' for information on a specific command."
-;;
-*)
-  file="$(command_path "$command")"
+    if [[ ! -h "$file" ]]; then
+      local summary="" usage="" help=""
 
-  if [ -n "$file" ]; then
-    print_help "$file"
+      eval "$(documentation_for "$file")"
+
+      if [[ "${summary:-}" ]]; then
+        commands["${#commands[@]}"]="$command"
+        summaries["${#summaries[@]}"]="$summary"
+
+        if [[ "${#command}" -gt "$longest_command" ]]; then
+          longest_command="${#command}"
+        fi
+      fi
+    fi
+  done
+
+  columns="$(tput cols)"
+  summary_length=$(( columns - longest_command - 4 ))
+
+  for (( index=0; index < ${#commands[@]}; index++ )); do
+    printf "  %-${longest_command}s  %s\\n" "${commands[$index]}" \
+      "$(truncate "${summary_length}" "${summaries[$index]}")"
+  done
+}
+
+# Formats STDIN for final output.
+format() {
+  { if [[ "${ansi:-}" ]]; then
+      sed -E "s/^([A-Z0-9][A-Z0-9 ]+)\$/$(tput bold)\\1$(tput sgr0)/"
+    else
+      cat
+    fi
+  } | awk '
+      /[[:graph:]]/ { p=1; for (i=1; i<=n; i++) print ""; n=0; print; }
+      p && /^[[:space:]]*$/ { n++ }
+    '
+}
+
+# Print help docs for the given file.
+#
+# $1 - file
+# $2 - section (default `all`, allowed: `all`, `usage`)
+print_help() {
+  local file="$1"
+  local section="${2:-all}"
+  local summary usage help
+
+  [[ -f "$file" ]] || abort "file '$file' does not exist."
+
+  eval "$(documentation_for "$file")"
+
+  [[ -z "${help:-}" ]] && help="${summary:-}"
+
+  if [[ "${usage:-}" ]]; then
+    [[ "${section}" =~ ^(usage|all)$ ]] && echo "$usage"
+
+    if [[ "$section" = "all" ]] && [[ "${help:-}" ]]; then
+      echo
+      echo "$help" | format
+    fi
   else
-    echo "sub: no such command \`$command'" >&2
-    exit 1
+    abort "sorry, this command isn't documented yet."
   fi
-esac
+}
+
+# Prints raw help docs from the given file with comments removed.
+extract_initial_comment_block() {
+  sed -ne "
+    /^#/ !{
+      q
+    }
+
+    s/^#$/# /
+
+    /^# / {
+      s/^# //
+      p
+    }
+  "
+}
+
+# Parses Summary, Usage, and Help info from documentation on STDIN. If Usage
+# or Summary are found, output can be used by `eval` to assign `$summary`,
+# `$usage`, and `$help`.
+collect_documentation() {
+  awk '
+    /^Summary:/ {
+      summary = substr($0, 10)
+      next
+    }
+
+    /^Usage:/ {
+      reading_usage = 1
+      usage = usage "\n" $0
+      next
+    }
+
+    /^( *$|       )/ && reading_usage {
+      usage = usage "\n" $0
+      next
+    }
+
+    {
+      reading_usage = 0
+      help = help "\n" $0
+    }
+
+    function escape(str) {
+      gsub(/[`\\$"]/, "\\\\&", str)
+      return str
+    }
+
+    function trim(str) {
+      sub(/^\n*/, "", str)
+      sub(/\n*$/, "", str)
+      return str
+    }
+
+    END {
+      if (usage || summary) {
+        print "summary=\"" escape(summary) "\""
+        print "usage=\"" escape(trim(usage)) "\""
+        print "help=\"" escape(trim(help)) "\""
+      }
+    }
+  '
+}
+
+# Gets documentation for the given filename. If or Summary are found, output
+# can be used by `eval` to assign `$summary`, `$usage`, and `$help`.
+#
+# Example
+#   local summary usage help
+#   eval "$(documentation_for "path/to/command")"
+documentation_for() {
+  local filename="$1"
+
+  if [[ -n "$filename" ]]; then
+    extract_initial_comment_block < "$filename" | collect_documentation
+  fi
+}
+
+main() {
+  local argv field file summaries
+
+  argv=$(getopt \
+    --name "sub ${0##*/sub-}" \
+    --options e:f:u \
+    --longoptions complete,exit:,flag:,usage \
+    -- \
+    "$@"
+  ) || return $?
+
+  eval "set -- $argv"
+
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+      --complete) completions;;
+      -e | --exit) exit_code="$2"; shift 2;;
+      -f | --flag)
+        case "$2" in
+          -h) field=usage; shift 2;;
+          --help) field=all; shift 2;;
+          *) abort "invalid flag '$2'";;
+        esac
+        ;;
+      -u | --usage) field=usage; shift;;
+      --) shift; break;;
+      *) break;;
+    esac
+  done
+
+  if [[ "${1:-}" ]]; then
+    file="$(command_path "$1")"
+
+    if [[ "$file" ]]; then
+      print_help "$file" "${field:-all}"
+    else
+      abort "no such command \`$1'"
+    fi
+  else
+    summaries="$(print_summaries)"
+
+    print_help "$(command -v sub)" "${field:-all}"
+
+    if [[ "${field:-all}" = "all" ]]; then
+      echo
+      echo "COMMANDS" | format
+      echo "$summaries"
+      echo
+      echo "See \`sub help <command>' for information on a specific command."
+    fi
+  fi
+
+  return "${exit_code:-0}"
+}
+
+main "$@"
diff --git a/libexec/sub-init b/libexec/sub-init
--- a/libexec/sub-init
+++ b/libexec/sub-init
@@ -1,94 +1,93 @@
 #!/usr/bin/env bash
-set -e
+# Usage: sub init [options] [--] [-]
+# Summary: Initializes Bash/ZSH shell completion for sub commands
+#
+# NAME
+#   sub init -- Initializes Bash/ZSH shell completion for
+#   sub commands
+#
+# SYNOPSIS
+#   sub init
+#   sub init [options] -
+#
+# DESCRIPTION
+#   Initializes Bash/ZSH shell completion for sub commands. This is
+#   NOT required unless you want the convenience of tab completion.
+#
+# OPTIONS
+#   -s shell, --shell shell
+#       Specify the shell to initialize for, default is `basename "$SHELL"`
+#
+# EXAMPLES
+#   Add to your `~/.zshenv` or `~/.bash_profile`
+#
+#     # Setup sub
+#     command -v sub > /dev/null && eval "$(sub init -)"
 
-print=""
-if [ "$1" = "-" ]; then
-  print=1
-  shift
+[[ "${DEBUG}" ]] && set -x
+
+set -euo pipefail
+
+while [[ "${#}" -gt 0 ]]; do
+  case "${1}" in
+    -s | --shell | --shell=*)
+      opt="${1%%=*}"
+      if [[ "${1:-}" = "--shell="* ]]; then
+        shell="${1##--shell=}"
+        shift
+      elif [[ "${2:-}" ]]; then
+        shell="${2}"
+        shift 2
+      fi
+
+      [[ -z "${shell:-}" ]] &&
+        abort "option requires an argument -- '${opt}'"
+      ;;
+    -s?*)
+      shell="${1##-s}"
+      shift
+      ;;
+    --) shift;;
+    -) print=1; shift;;
+    --*|-*) warn "Invalid option"; exec sub-help --usage --exit 1 "${0##*/sub-}";;
+    *) break;;
+  esac
+done
+
+if [[ -z "${shell:-}" ]]; then
+  shell="$(basename "${SHELL}")"
 fi
 
-shell="$1"
-if [ -z "$shell" ]; then
-  shell="$(basename "$SHELL")"
-fi
-
-resolve_link() {
-  $(type -p greadlink readlink | head -1) $1
-}
-
-abs_dirname() {
-  local cwd="$(pwd)"
-  local path="$1"
-
-  while [ -n "$path" ]; do
-    cd "${path%/*}"
-    local name="${path##*/}"
-    path="$(resolve_link "$name" || true)"
-  done
-
-  pwd
-  cd "$cwd"
-}
-
-root="$(abs_dirname "$0")/.."
-
-if [ -z "$print" ]; then
-  case "$shell" in
-  bash )
-    profile='~/.bash_profile'
-    ;;
-  zsh )
-    profile='~/.zshenv'
-    ;;
-  * )
-    profile='your profile'
-    ;;
+if [[ -z "${print:-}" ]]; then
+  case "${shell}" in
+    bash)
+      # shellcheck disable=SC2088
+      profile='~/.bash_profile'
+      ;;
+    zsh)
+      # shellcheck disable=SC2088
+      profile='~/.zshenv'
+      ;;
+    *)
+      profile='your profile'
+      ;;
   esac
 
   { echo "# Load sub automatically by adding"
     echo "# the following to ${profile}:"
     echo
     echo "eval \"\$(${_SUB_ROOT}/bin/sub init -)\""
-    echo
   } >&2
 
   exit 1
 fi
 
-echo "export PATH=\"\${PATH}:${_SUB_ROOT}/bin\""
-
-case "$shell" in
-bash | zsh )
-  echo "source \"$root/completions/sub.${shell}\""
-  ;;
-esac
-
-commands=(`sub commands --sh`)
-IFS="|"
-cat <<EOS
-_sub_wrapper() {
-  local command="\$1"
-  if [ "\$#" -gt 0 ]; then
-    shift
-  fi
-
-  case "\$command" in
-  ${commands[*]})
-    eval \`sub "sh-\$command" "\$@"\`;;
-  *)
-    command sub "\$command" "\$@";;
-  esac
-}
-EOS
-
-# zsh can't pass argument with aliases, but bash can.
-# zsh can have functions with the name being only numbers, but bash can't.
-# fix both cases here by letting zsh have a function, and bash have its alias.
-case "$shell" in
-bash )
-  echo "alias sub=_sub_wrapper"
-  ;;
-zsh )
-  echo "sub=_sub_wrapper"
-  ;;
+case "${shell}" in
+  bash | zsh)
+    echo "if ! command -v sub > /dev/null; then"
+    echo "  export PATH=\"\${PATH}:${_SUB_ROOT}/bin\""
+    echo "fi"
+    echo
+    echo "source \"${_SUB_ROOT}/completions/sub.${shell}\""
+    ;;
 esac
